sudo: required

services:
- docker

language: generic

jobs:
  include:
    # Latest image build/push
    - if: branch = master
      script:
        - make latest && make test
      deploy:
        provider: script
        script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push-latest
    # For release purpose
    - if: tag IS present
      script:
        - make versioned && make test
      deploy:
        on:
          tags: true
        provider: script
        script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push-versioned