name: PR
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ./src/github.com/${{ github.repository }}
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # check out actual commit that triggered event
          ref: ${{ github.event.pull_request.head.sha }}
          path: ./src/github.com/${{ github.repository }}
          fetch-depth: 0
      - name: Build
        run: |
          make docker-build
      - name: Testing
        run: |
          make test-gen test-check
      - name: Tests failure
        if: ${{ failure() }}
        run: |
          timeout 10s make test-clean
