name: Push
on:
  push:
    branches:
      - master
  release:
jobs:
  test:
    name: image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./src/github.com/${{ github.repository }}
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # check out actual commit that triggered event
          ref: ${{ github.event.pull_request.head.sha }}
          path: ./src/github.com/${{ github.repository }}
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: |
          make docker-build
      - name: Testing
        run: |
          make test-gen test-check
      - name: Tests failure
        if: ${{ failure() }}
        run: |
          timeout 10s make test-clean
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push image
        run: |
          make push-versioned
