name: Push
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./src/github.com/${{ github.repository }}
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # check out actual commit that triggered event
          ref: ${{ github.event.pull_request.head.sha }}
          path: ./src/github.com/${{ github.repository }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: |
          make latest && make versioned
      - name: Push image
        run: |
          make push-versioned
